name: suppfig1
channels:
  - conda-forge
  - bioconda
  - main
  - r
dependencies:
  - nextflow=22.04.0
  - R
  - r-ggplot2
  - bioconductor-biostrings
  - r-tidyverse
  - r-gridgraphics
  - r-gridextra
  - r-plotrix
  - r-rcolorbrewer
  - sra-tools=2.10.1
